# Environment file for secrets (such as remote tokens).
# string = none | <path>
env_file: none

# All parameters about the templates.
templates:
  # Path for templates. If a template is not found, it will be replaced by the default one if it exists.
  # string = default | <path>
  template_paths: default
  # If a template is not found, decide if the pipeline has to be cancelled.
  # boolean = true | false
  cancel_if_error: true

  # If there is online templates on a git remote, provide it here.
  remote_templates:
    # The name of the remote template, and the URL of the remote.
    # name: string = none | <name>
    # url: string = none | <url>
    - name: none
      url: none

# Default values for SpinUp.
defaults:
  # If a front-end service should be generated.
  # boolean = true | false
  frontend_enabled: true
  # The default front-end template name.
  # string = <name>
  frontend: "vue"
  # If a back-end service should be generated.
  # boolean = true | false
  backend_enabled: true
  # The default back-end template name.
  # string = <name>
  backend: "go"
  # If a database service should be generated.
  # boolean = true | false
  database_enabled: true
  # The default database template name.
  # string = <name>
  database: "postgres"
  # The default name of a project.
  # string = <name>
  project_name: "web-app"
  # If this option is enabled, the application will be containerized in a docker-compose.
  # boolean = true | false
  docker: true
  # The default package manager for Node.js
  # string = <package_manager>
  package_manager: "npm"
  # The default front-end exposed port.
  # int = <unique_port>
  frontend_port: 3000
  # The default back-end exposed port.
  # int = <unique_port>
  backend_port: 3000

# Options related to CLI
cli:
  # Enable this if you want a ton of logs when you execute commands.
  # boolean = true | false
  verbose: true
